### PR TITLE
PR: Update recipe to not build for python <=3.5

### PR DESCRIPTION
**Pull request by dalthviz**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by dalthviz** [comment]
@conda-forge-admin, please rerender

**Comment by dalthviz** [comment]
For this I followed what is done in conda/conda#5971 and the docs: https://conda-forge.org/docs/maintainer/knowledge_base.html#noarch-python

Fixes spyder-ide/spyder#13605
Fixes davidhalter/parso#149

pinging @ccordoba12 and @isidentical just in case

**Comment by ccordoba12** [comment]
Looks good to me. Thanks @dalthviz!

**Comment by rhuffy** [comment]
@synapticarbors @iron0012 Can this be merged asap?

**Pull request merged**
